package container

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const slicePolicyDropinFile = "piccolo-resources.conf"
const adaptiveMemoryBaselinePrefix = "# Piccolod adaptive MemoryHigh baseline="
const slicePolicyApplyTimeout = 10 * time.Second

// dropinRootForTest lets tests redirect the slice drop-in root away from
// the real /etc/systemd/system/ (which requires root + is global state).
// Production code path leaves it empty; tests set it to t.TempDir().
var dropinRootForTest = ""

func slicePolicyDropinRoot() string {
	if dropinRootForTest != "" {
		return dropinRootForTest
	}
	return "/etc/systemd/system"
}

// SliceResourcePolicy encapsulates cgroup v2 resource limits applied at
// the per-app-user slice (user-<UID>.slice). These knobs are enforced
// hierarchically by the kernel and cover all containers run by the app's
// runtime user.
//
// All fields are optional individually:
//   - MemoryHighBytes + MemoryMaxBytes: if both zero, memory knobs are
//     omitted. Must be set together (one without the other is rejected).
//   - CPUWeight: if zero, CPUWeight is omitted (kernel default 100).
//
// An all-zero policy writes no drop-in file; callers should use Remove()
// or Apply() which will drop the file and reset live state.
type SliceResourcePolicy struct {
	UID             uint32
	MemoryHighBytes int64
	MemoryMaxBytes  int64
	CPUWeight       int
	// BaselineMemoryHighBytes identifies a pressure-relieved MemoryHigh derived
	// from this baseline. It is not a second systemd property.
	BaselineMemoryHighBytes int64
}

// DropinDir returns the slice-specific drop-in directory.
func (p SliceResourcePolicy) DropinDir() string {
	return filepath.Join(slicePolicyDropinRoot(), fmt.Sprintf("user-%d.slice.d", p.UID))
}

// DropinFile returns the absolute path of the piccolod-owned drop-in.
func (p SliceResourcePolicy) DropinFile() string {
	return filepath.Join(p.DropinDir(), slicePolicyDropinFile)
}

// SliceUnit returns the systemd unit name for the slice.
func (p SliceResourcePolicy) SliceUnit() string {
	return fmt.Sprintf("user-%d.slice", p.UID)
}

// IsEmpty reports whether no policy fields are set.
func (p SliceResourcePolicy) IsEmpty() bool {
	return p.MemoryHighBytes == 0 && p.MemoryMaxBytes == 0 && p.CPUWeight == 0
}

// Validate returns an error for malformed policies.
func (p SliceResourcePolicy) Validate() error {
	if p.UID == 0 {
		return fmt.Errorf("slice policy: UID must be non-zero")
	}
	if p.MemoryHighBytes < 0 || p.MemoryMaxBytes < 0 {
		return fmt.Errorf("slice policy: memory limits must be non-negative")
	}
	if (p.MemoryHighBytes == 0) != (p.MemoryMaxBytes == 0) {
		return fmt.Errorf("slice policy: MemoryHigh and MemoryMax must be set together")
	}
	if p.MemoryHighBytes > 0 && p.MemoryHighBytes > p.MemoryMaxBytes {
		return fmt.Errorf("slice policy: MemoryHigh (%d) must be <= MemoryMax (%d)",
			p.MemoryHighBytes, p.MemoryMaxBytes)
	}
	if p.BaselineMemoryHighBytes < 0 || (p.BaselineMemoryHighBytes > 0 &&
		(p.MemoryHighBytes == 0 || p.BaselineMemoryHighBytes > p.MemoryHighBytes)) {
		return fmt.Errorf("slice policy: adaptive MemoryHigh baseline must be positive and <= MemoryHigh")
	}
	if p.CPUWeight < 0 || p.CPUWeight > 10000 {
		return fmt.Errorf("slice policy: CPUWeight %d out of valid range 0-10000", p.CPUWeight)
	}
	return nil
}

// Render returns the drop-in file content. Returns empty string if the
// policy has no fields set (caller should Remove() any stale drop-in).
func (p SliceResourcePolicy) Render() string {
	if p.IsEmpty() {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by piccolod. Do not edit by hand.\n")
	if p.BaselineMemoryHighBytes > 0 && p.MemoryHighBytes > p.BaselineMemoryHighBytes {
		fmt.Fprintf(&b, "%s%d\n", adaptiveMemoryBaselinePrefix, p.BaselineMemoryHighBytes)
	}
	b.WriteString("[Slice]\n")
	if p.MemoryHighBytes > 0 {
		fmt.Fprintf(&b, "MemoryHigh=%d\n", p.MemoryHighBytes)
	}
	if p.MemoryMaxBytes > 0 {
		fmt.Fprintf(&b, "MemoryMax=%d\n", p.MemoryMaxBytes)
	}
	if p.CPUWeight > 0 {
		fmt.Fprintf(&b, "CPUWeight=%d\n", p.CPUWeight)
	}
	return b.String()
}

// RestoreAdaptiveMemoryHigh retains a saved pressure adjustment only while its
// complete generated policy still matches this current baseline. Manual and
// malformed files are not adaptive state. Changes to baseline, max, or CPUWeight
// invalidate an old adjustment. The caller must supply the unadjusted policy.
func (p SliceResourcePolicy) RestoreAdaptiveMemoryHigh() (SliceResourcePolicy, error) {
	if err := p.Validate(); err != nil {
		return p, err
	}
	if p.BaselineMemoryHighBytes != 0 {
		return p, fmt.Errorf("slice policy: restore requires an unadjusted baseline policy")
	}
	if p.MemoryHighBytes == 0 {
		return p, nil
	}
	content, err := os.ReadFile(p.DropinFile())
	if err != nil {
		if os.IsNotExist(err) {
			return p, nil
		}
		return p, fmt.Errorf("slice policy: read adaptive policy %s: %w", p.DropinFile(), err)
	}
	var baseline, high int64
	for _, line := range strings.Split(string(content), "\n") {
		switch {
		case strings.HasPrefix(line, adaptiveMemoryBaselinePrefix):
			baseline, err = strconv.ParseInt(strings.TrimPrefix(line, adaptiveMemoryBaselinePrefix), 10, 64)
		case strings.HasPrefix(line, "MemoryHigh="):
			high, err = strconv.ParseInt(strings.TrimPrefix(line, "MemoryHigh="), 10, 64)
		default:
			continue
		}
		if err != nil {
			return p, nil
		}
	}
	if baseline != p.MemoryHighBytes || high <= baseline || high > p.MemoryMaxBytes {
		return p, nil
	}
	candidate := p
	candidate.BaselineMemoryHighBytes = baseline
	candidate.MemoryHighBytes = high
	if candidate.Validate() != nil || candidate.Render() != string(content) {
		return p, nil
	}
	return candidate, nil
}

// writeFile persists the drop-in atomically (write-to-tmp + rename).
// Returns true if the on-disk content changed.
func (p SliceResourcePolicy) writeFile() (changed bool, err error) {
	content := p.Render()
	if content == "" {
		return p.removeFile()
	}

	path := p.DropinFile()
	if existing, rerr := os.ReadFile(path); rerr == nil && string(existing) == content {
		return false, nil
	}

	if err := os.MkdirAll(p.DropinDir(), 0o755); err != nil {
		return false, fmt.Errorf("slice policy: mkdir %s: %w", p.DropinDir(), err)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("slice policy: write tmp %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return false, fmt.Errorf("slice policy: rename %s → %s: %w", tmp, path, err)
	}
	return true, nil
}

// removeFile deletes the drop-in file if it exists. Idempotent.
// Returns true if the file existed and was removed.
func (p SliceResourcePolicy) removeFile() (removed bool, err error) {
	path := p.DropinFile()
	if err := os.Remove(path); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("slice policy: remove %s: %w", path, err)
	}
	return true, nil
}

// Apply writes (or removes) the drop-in and propagates the change live
// via systemctl daemon-reload + set-property. For empty policies, the
// slice's properties are reset to kernel defaults
// (MemoryHigh/MemoryMax=infinity, CPUWeight=100).
//
// The live-apply path runs on every Apply call regardless of whether
// the on-disk file changed. Rationale: a previous Apply() may have
// written the file successfully but failed to propagate live (systemctl
// transient error, daemon-reload mid-boot, etc). The periodic
// reconciler (plan P1.7) relies on re-entry to heal; short-circuiting
// on file-identity alone defeats that healing path and leaves the slice
// at kernel defaults indefinitely. set-property on an already-applied
// value is a cheap no-op at the kernel level.
func (p SliceResourcePolicy) Apply() error {
	return p.ApplyContext(context.Background())
}

// ApplyContext applies the persistent and live policy with cancellation and a
// bounded command budget. A live failure leaves the file available for retry.
func (p SliceResourcePolicy) ApplyContext(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, slicePolicyApplyTimeout)
	defer cancel()
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := p.Validate(); err != nil {
		return err
	}

	if p.IsEmpty() {
		changed, err := p.removeFile()
		if err != nil {
			return err
		}
		if changed {
			log.Printf("INFO: slice policy cleared for %s", p.SliceUnit())
		}
		return p.resetLive(ctx)
	}

	changed, err := p.writeFile()
	if err != nil {
		return err
	}
	if changed {
		log.Printf("INFO: slice policy written for %s (MemoryHigh=%d MemoryMax=%d CPUWeight=%d)",
			p.SliceUnit(), p.MemoryHighBytes, p.MemoryMaxBytes, p.CPUWeight)
	}
	return p.applyLive(ctx)
}

// Remove deletes the drop-in without resetting live slice state.
// Intended for uninstall paths where the slice itself is being torn down.
// Rejects UID=0 to mirror the Validate()/Apply() defensive posture —
// Remove() should never be able to unlink files under
// /etc/systemd/system/user-0.slice.d/ even if a future caller passes a
// corrupted credential.
func (p SliceResourcePolicy) Remove() error {
	if p.UID == 0 {
		return fmt.Errorf("slice policy: refusing to Remove with UID=0")
	}
	_, err := p.removeFile()
	if err == nil {
		log.Printf("INFO: slice policy drop-in removed for %s", p.SliceUnit())
	}
	return err
}

func (p SliceResourcePolicy) applyLive(ctx context.Context) error {
	if out, err := defaultExecutor.RunContext(ctx, "systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("slice policy: daemon-reload: %w: %s", err, strings.TrimSpace(string(out)))
	}
	args := []string{"set-property", p.SliceUnit()}
	if p.MemoryHighBytes > 0 {
		args = append(args, fmt.Sprintf("MemoryHigh=%d", p.MemoryHighBytes))
	}
	if p.MemoryMaxBytes > 0 {
		args = append(args, fmt.Sprintf("MemoryMax=%d", p.MemoryMaxBytes))
	}
	if p.CPUWeight > 0 {
		args = append(args, fmt.Sprintf("CPUWeight=%d", p.CPUWeight))
	}
	if out, err := defaultExecutor.RunContext(ctx, "systemctl", args...); err != nil {
		return fmt.Errorf("slice policy: set-property %s: %w: %s",
			p.SliceUnit(), err, strings.TrimSpace(string(out)))
	}
	return nil
}

func (p SliceResourcePolicy) resetLive(ctx context.Context) error {
	if out, err := defaultExecutor.RunContext(ctx, "systemctl", "daemon-reload"); err != nil {
		return fmt.Errorf("slice policy: daemon-reload: %w: %s", err, strings.TrimSpace(string(out)))
	}
	if out, err := defaultExecutor.RunContext(ctx, "systemctl", "set-property", p.SliceUnit(),
		"MemoryHigh=infinity", "MemoryMax=infinity", "CPUWeight=100"); err != nil {
		return fmt.Errorf("slice policy: set-property reset %s: %w: %s",
			p.SliceUnit(), err, strings.TrimSpace(string(out)))
	}
	return nil
}
