// Package captive implements the captive portal HTTP server for WiFi AP mode.
// It serves a single-page portal that lets users scan for and connect to WiFi
// networks with x25519 ECDH-encrypted passphrase transmission.
package captive

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"

	"golang.org/x/crypto/nacl/box"
)

// ECDHKeypair holds an x25519 keypair for NaCl box encryption.
// A fresh keypair is generated on each AP activation and the private key
// is zeroed on deactivation.
type ECDHKeypair struct {
	PublicKey  [32]byte
	PrivateKey [32]byte
}

// NewECDHKeypair generates a fresh x25519 keypair.
func NewECDHKeypair() (*ECDHKeypair, error) {
	pub, priv, err := box.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("ecdh: generate keypair: %w", err)
	}
	return &ECDHKeypair{PublicKey: *pub, PrivateKey: *priv}, nil
}

// PublicKeyBase64 returns the public key as a base64-encoded string for
// embedding in the HTML portal page.
func (kp *ECDHKeypair) PublicKeyBase64() string {
	return base64.StdEncoding.EncodeToString(kp.PublicKey[:])
}

// Decrypt decrypts a NaCl box sealed by the browser using TweetNaCl.js.
// clientPublicKey is the ephemeral public key generated by the browser.
// nonce is the 24-byte nonce. ciphertext is the encrypted passphrase.
func (kp *ECDHKeypair) Decrypt(clientPublicKey [32]byte, nonce [24]byte, ciphertext []byte) ([]byte, error) {
	plaintext, ok := box.Open(nil, ciphertext, &nonce, &clientPublicKey, &kp.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("ecdh: decryption failed (wrong key or corrupted ciphertext)")
	}
	return plaintext, nil
}

// Zero overwrites the private key material with zeros.
func (kp *ECDHKeypair) Zero() {
	for i := range kp.PrivateKey {
		kp.PrivateKey[i] = 0
	}
}

// decryptConnectRequest parses and decrypts the passphrase from a connect API
// request body. All fields are base64-encoded.
func decryptConnectRequest(kp *ECDHKeypair, clientPubB64, nonceB64, ciphertextB64 string) ([]byte, error) {
	clientPubBytes, err := base64.StdEncoding.DecodeString(clientPubB64)
	if err != nil || len(clientPubBytes) != 32 {
		return nil, fmt.Errorf("invalid client public key")
	}

	nonceBytes, err := base64.StdEncoding.DecodeString(nonceB64)
	if err != nil || len(nonceBytes) != 24 {
		return nil, fmt.Errorf("invalid nonce")
	}

	ciphertext, err := base64.StdEncoding.DecodeString(ciphertextB64)
	if err != nil || len(ciphertext) == 0 {
		return nil, fmt.Errorf("invalid ciphertext")
	}

	var clientPub [32]byte
	var nonce [24]byte
	copy(clientPub[:], clientPubBytes)
	copy(nonce[:], nonceBytes)

	return kp.Decrypt(clientPub, nonce, ciphertext)
}
